project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - cv.qmd
    - econometrics.qmd
    - EnergyMod.qmd
    - conferences.qmd
    - contact.qmd

website:
  title: "Luis Sarmiento -- Economist"
  navbar:
    search: true
    pinned: true
    collapse: true
    favicon: pictures/headshot.jpeg
    right:
      - text: Home
        href: index.qmd 
      - text: CV
        href: cv.qmd 
      - icon: github
        href: https://github.com/gsaabogado
      - icon: twitter
        href: https://twitter.com/gsaabogado
      - icon: linkedin 
        href: https://www.linkedin.com/in/luis-sarmiento-eco 
      - text: Institutional Site
        href: https://www.eiee.org/member/luis-alejandro-sarmiento/
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Sections"
        contents:
        - index.qmd
        - cv.qmd
        - econometrics.qmd
        - EnergyMod.qmd
        - conferences.qmd
        - contact.qmd

format:
  html:
    theme: 
      - flatly
      - costum.scss
    


    
    



