---
title: "{{< fa person-chalkboard >}} Conferences"
# uncomment this line to produce HTML and PDF in RStudio:
#knit: pagedown::chrome_print
format: 
  html:
    theme: [flatly, costum.scss]
    fontsize: 0.85em
    toc: true
    always_allow_html: true
---
```{r}
#| echo: false 
fivethirtyeight <- function(font_size = 12,
                            font_color = "#222222",
                            header_font_size = 12,
                            header_font_color = "#000000",
                            background_color = "transparent",
                            cell_padding = 5,
                            centered = FALSE) {
  
  if (!is.logical(centered)) {
    
    stop("`centered` must be TRUE or FALSE")
  }
  
  if (centered == TRUE) {
    
    centered_content = list(display = "flex", flexDirection = "column", justifyContent = "center")
    
  } else { centered_content = NULL }
  
  reactableTheme(
    cellStyle = centered_content,
    color = font_color,
    backgroundColor = background_color,
    borderWidth = "1.25px",
    borderColor = "black",
    stripedColor = "#dddddd",
    highlightColor = "#f0f0f0",
    cellPadding = cell_padding,
    tableStyle = list(
      fontSize = font_size,
      borderBottom = "3px solid #222222"
    ),
    headerStyle = list(
      borderWidth = "5px",
      paddingTop = "12px",
      verticalAlign = "bottom",
      textAlign = "bottom",
      background = "transparent",
      textTransform = "uppercase",
      borderColor = "#222222",
      color = header_font_color,
      "&:hover" = list(background = "#dddddd"),
      "&[aria-sort='ascending'], &[aria-sort='descending']" = list(background = "#5b5e5f", color = "#ffffff"),
      borderColor = "#333",
      fontSize = header_font_size
    ),
    groupHeaderStyle = list(
      "&:not(:empty)" = list(
        paddingBottom = "3px",
        verticalAlign = "bottom",
        textAlign = "bottom",
        backgroundColor = "#ffffff",
        textTransform = "uppercase",
        fontSize = header_font_size,
        color = font_color
      )
    ),
    searchInputStyle = list(
      textTransform = "uppercase",
      color = "#222222",
      fontSize = "14px"
    ),
    inputStyle = list(backgroundColor = "#ffffff", color = "#222222"),
    rowSelectedStyle = list(backgroundColor = "#dddddd"),
    pageButtonStyle = list(textTransform = "uppercase", fontSize = "14px"),
    paginationStyle = list(textTransform = "uppercase", fontSize = "14px")
  )
}

```

```{r}
#| echo: false 
#| warning: false
#### Load the data ####
file = gsub("/02_cv", "", getwd())
conf = read_excel(paste0(file, "/Codebook.xlsx"), sheet = "Conferences")

#### Construct the table ####
reactable(
  conf, theme = fivethirtyeight(),
  defaultColDef = colDef(align = "left"), 
  columns = list(City = colDef(maxWidth = 100), 
                 Conference = colDef(maxWidth = 400),
                 Presentation = colDef(maxWidth = 400),
                 Year = colDef(maxWidth = 50, style = color_scales(conf, colors = c("gray", "#0b263d"))), 
                 Country = colDef(cell = embed_img(height = "25", width = "25"), maxWidth = 100, align = "center"))
  )
```